[package]
name = "developer_portal"
version = "1.0.0"
authors = [
  "Jayden Dang <jayden.vu@movementlabs.xyz>"
]
license = "Apache-2.0"

[addresses]
movement = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
