[package]
name = "developer_portal"
version = "1.0.0"
authors = [
  "Jayden Dang <jayden.vu@movementlabs.xyz>"
]
license = "MIT"

[addresses]
movement = "0xc103109311944d8bae02fccf9273dcb4615be30653e85aec628f04b6ddd00fef"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
